# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :ios_testflight_app do
    match(
      type: "appstore", 
      readonly: true, 
      force_for_new_devices: true
    )

    build_app(
        scheme: "Runner",
        archive_path: "./build/Runner.xcarchive",
        export_method: "app-store",
        output_directory: "./build/Runner"
    )

    upload_to_testflight(
      api_key_path: './fastlane/AuthKey_ZWW7PY96N4.json',
      beta_app_feedback_email: "jb@dokoni.co.jp",
      demo_account_required: false,
      notify_external_testers: false,
      distribute_external: true,
      groups: ['Beta Testers', 'Internal Testers'],
      changelog: "This will overwrite the App from the App Store. What you do in this version of the app has impact on the App from the App Store. This is not a different environment.",
    )
  end
end